### ISSUE TITLE
room seed number copy button

### ISSUE THREAD

**Issue by samslow** [gorisanson/pikachu-volleyball-p2p-online#16]
Hello. I am enjoying p2p online with my friend.

However, it is inconvenient to drag the number after pressing the rooming button every time

so I want to make a room seed number copy button.

At first, I was going to do it. because i thought this is so easy things

but.. I couldn't try because of the error below.

![image](https://user-images.githubusercontent.com/26738367/85922144-0413f280-b8bc-11ea-8799-5a644b1e0866.png)

It appears to occur because the `firebase config` can't be downloaded by github.

If you give me a guide to give me a contribution, 

I want to modify other things besides this.

**Comment by gorisanson** [comment]
@samslow 

Thanks! I think it would be a good enhancement!

There are template files for them:
[`src/resources/js/data_channel/firebase_config.template.js`](https://github.com/gorisanson/pikachu-volleyball-p2p-online/blob/3b3f1a3828f73361cccba6d2c28b72f4dd1fa53e/src/resources/js/data_channel/firebase_config.template.js)
[`src/resources/js/quick_match/quick_match_server_url.template.js`](https://github.com/gorisanson/pikachu-volleyball-p2p-online/blob/3b3f1a3828f73361cccba6d2c28b72f4dd1fa53e/src/resources/js/quick_match/quick_match_server_url.template.js)

How to set `firebase_config.js`:
(1) [Create a Cloud Firestore database](https://firebase.google.com/docs/firestore/quickstart#create)
(2) Populate the file `firebase_config.template.js` with [Firebase config object](https://firebase.google.com/docs/web/setup#config-object)
(3) Rename the file to `firebase_config.js`

For `quick_match_server_url.js`, since you're not testing the quick match mode, it would be enough just to rename the file `quick_match_server_url.template.js` to `quick_match_server_url.js`.

I hope this comment would be helpful.

**Comment by samslow** [comment]
ok i will fix it now
